language: php

services:
  - mysql
  - postgresql

php:
  - 7.4
  - 7.3
  - 7.2

env:
  - DB=mysql LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
  - DB=mysql LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
  - DB=mysql LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0
  - DB=pgsql LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
  - DB=pgsql LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
  - DB=pgsql LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0
  - DB=sqlite LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
  - DB=sqlite LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
  - DB=sqlite LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0
  - DB=sqlsrv LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
  - DB=sqlsrv LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
  - DB=sqlsrv LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0

matrix:
  # PHP 7.3 passes but 7.4 and 7.2 fails in Travis because of the SQLite driver version
  # https://travis-ci.com/mpyw/compoships-eager-limit/builds/151876198
  exclude:
    - php: 7.4
      env: DB=sqlite LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
    - php: 7.4
      env: DB=sqlite LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
    - php: 7.4
      env: DB=sqlite LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0
    - php: 7.2
      env: DB=sqlite LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
    - php: 7.2
      env: DB=sqlite LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
    - php: 7.2
      env: DB=sqlite LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist --prefer-stable

before_script:
  - mkdir -p build/logs
  - composer require "laravel/framework:${LARAVEL_VERSION}" "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - composer update
  - cp tests/config/database.travis.php tests/config/database.php
  - mysql -e 'create database `test`;'
  - psql -c 'create database "test";' -U postgres
  - |
    if [ $DB == "sqlsrv" ]; then
      curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list | sudo tee /etc/apt/sources.list.d/mssql-server-2017.list
      sudo apt-get update
      sudo apt-get install mssql-server
      sudo MSSQL_SA_PASSWORD=Password! MSSQL_PID=developer /opt/mssql/bin/mssql-conf -n setup accept-eula
      curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
      curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
      sudo apt-get update
      sudo ACCEPT_EULA=Y apt-get install mssql-tools unixodbc-dev
      pecl install pdo_sqlsrv
      sudo /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Password! -Q "create database [test]"
    fi

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - |
    travis_retry wget https://scrutinizer-ci.com/ocular.phar
    travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
